[package]
name = "memory-proof-script"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "memory_prove"
path = "src/bin/memory_prove.rs"

[dependencies]
sp1-sdk = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
sp1-build = "4.0.0"